# Generated by Django 5.2 on 2025-04-30 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_name',
        ),
        migrations.AddField(
            model_name='product',
            name='cat_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kglapp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
