# Generated by Django 5.2 on 2025-04-30 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0003_rename_cat_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_stock',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
