# Generated by Django 5.2 on 2025-05-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0005_alter_product_image_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('passward', models.CharField(max_length=255)),
            ],
        ),
    ]
