# Generated by Django 5.2 on 2025-05-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0006_usar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
