# Generated by Django 5.2 on 2025-05-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0007_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kglapp.product'),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kglapp.branch'),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kglapp.customer'),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kglapp.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kglapp.branch'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kglapp.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kglapp.category'),
        ),
    ]
