# Generated by Django 5.2 on 2025-05-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0008_alter_branch_product_name_alter_creditsale_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
