# Generated by Django 5.2 on 2025-05-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0009_alter_product_supplier_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='product_name',
            new_name='product',
        ),
    ]
