# Generated by Django 5.2 on 2025-05-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0010_rename_product_name_branch_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
