# Generated by Django 5.2 on 2025-05-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0011_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='sku',
        ),
    ]
