# Generated by Django 5.2 on 2025-05-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0012_remove_inventory_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='buying_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
