# Generated by Django 5.2 on 2025-05-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0013_alter_inventory_buying_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unite_of_measure',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
