# Generated by Django 5.2 on 2025-05-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0014_alter_inventory_unite_of_measure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usar',
        ),
    ]
