# Generated by Django 5.2 on 2025-05-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0016_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount_paid',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='balance',
            field=models.FloatField(default=10),
        ),
    ]
